### ISSUE TITLE
how you build live demo examples, is it auto generated ? 

### ISSUE THREAD

**Issue by omarazmi** [thoughtbot/sassdoc-theme-neat#3]
the demo examples, 
how you build it? 
how to use it if i use your theme?
can i get the bourbon develop files that you generate the documentation from it ?

**Comment by tysongach** [comment]
@omarazmi Are you speaking of these? http://neat.bourbon.io/examples/

**Comment by omarazmi** [comment]
i speak about this sassdoc theme used to generate sass documentation [here](http://bourbon.io/docs/).
i would like to see how the [demo section](http://bourbon.io/docs/#animation) generated from sass files, what are the annotation used and how ?

your help appreciated, thanks.

**Comment by tysongach** [comment]
@omarazmi Ah! Those Bourbon docs are not currently using SassDoc, actually. Though, we are in the process of moving Bourbon to use SassDoc. Neat is currently the only one using it.

**Comment by omarazmi** [comment]
aha, thanks.
